Enable use of replacement patterns in moduleNameMapper
JoinColony/eslint-import-resolver-jest pull request #1
Opened 2017-08-22 23:25 UTC by samtgarson

We're using regex replacements in our `moduleNameMappers` which is working with Jest but not with `eslint`... Here's a small change to get them working.

Find an example in the new test case.

Thanks for the OSS!

2017-08-23 15:57 UTC, chmanie requested changes
Thank you so much for your contribution! I didn’t really need of this use case. If you don’t mind, could you correct the few minor issues? Otherwise I’ll do it.

2017-08-23 15:57 UTC, chmanie commented on .gitignore
> +node_modules
This should be in your global `.gitignore`, not here :)

2017-08-23 15:57 UTC, chmanie commented on index.js
> +    var regex = new RegExp(moduleNameMappers[i])
Would you mind adding the missing semicolons here, for consistency? (+ line 53)

2017-08-24 08:30 UTC, samtgarson commented
All done! 

Happy to move the `node_modules` here but that is an artifact of your application, not of your environment so I personally believe it should be in your application's `.gitignore`... otherwise anyone who works on your code has to replicate your environment.

Thanks for the review 😁

2017-08-24 18:39 UTC, chmanie commented
> but that is an artifact of your application, not of your environment so I personally believe it should be in your application's .gitignore

I do agree with that. Will add it.

Thanks for the PR!

2017-08-24 18:40 UTC, chmanie approved these changes

2017-08-24 18:40 UTC, merged

2017-08-24 18:44 UTC, chmanie commented
Will bump the version to 1.0.1 as this is not breaking anything (afaic) and should have worked from the beginning.